# Generated by Django 6.1.1 on 2026-09-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('hybrid', 'Hybrid')], max_length=20)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12)),
                ('one_day_change_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_trending', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pnl_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=4, max_digits=14)),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='funds.fund')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='funds.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('units', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='funds.fund')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funds.portfolio')),
            ],
        ),
    ]
