# Generated by Django 6.1.1 on 2026-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskRecompute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('error', models.TextField(help_text='Full exception message from the failed compute call.')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('failed', 'Failed'), ('recovered', 'Recovered'), ('exhausted', 'Exhausted (max retries reached)')], db_index=True, default='failed', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of retry attempts made by retry_failed_portfolio_recomputes.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set when status transitions to RECOVERED or EXHAUSTED.', null=True)),
            ],
            options={
                'verbose_name': 'Failed Recompute (DLQ)',
                'verbose_name_plural': 'Failed Recomputes (DLQ)',
                'ordering': ['-failed_at'],
            },
        ),
    ]
