# Generated by Django 6.1.1 on 2026-09-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rollout_percentage__gte', 0), ('rollout_percentage__lte', 100)), name='rollout_percentage_between_0_and_100')],
            },
        ),
        migrations.CreateModel(
            name='TargetingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('in', 'In'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('contains', 'Contains')], max_length=20)),
                ('value', models.JSONField()),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeting_rules', to='flags.featureflag')),
            ],
        ),
    ]
