# Generated by Django 6.1.1 on 2026-09-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('schema', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('min_app_version', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='screens.screen')),
                ('widget_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='screens.widgettype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LayoutVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('sections_snapshot', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.CharField(blank=True, default='', max_length=150)),
                ('is_current', models.BooleanField(default=False)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_versions', to='screens.screen')),
            ],
            options={
                'ordering': ['-version_number'],
                'constraints': [models.UniqueConstraint(fields=('screen', 'version_number'), name='unique_screen_version_number')],
            },
        ),
    ]
