# Generated by Django 6.1.1 on 2026-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='layoutversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('screen',), name='unique_current_layout_version_per_screen'),
        ),
    ]
