"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
Environment variables are loaded from a .env file via python-dotenv.
See .env.example for all required variables.
"""

import os
from pathlib import Path

import sentry_sdk
from celery.schedules import crontab
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file at project root
load_dotenv(BASE_DIR / ".env")

# ---------------------------------------------------------------------------
# prometheus_client multiprocess mode -- the Django web process and the
# Celery worker process are separate OS processes with separate memory, so
# a plain in-memory prometheus_client registry in one is invisible to the
# other. This must be set before prometheus_client is first imported
# anywhere (apps/common/cache.py, middleware.py, metrics.py), so it lives
# here, right after load_dotenv(). See apps/common/views.py::metrics_view
# for the matching MultiProcessCollector read side.
# ---------------------------------------------------------------------------
PROMETHEUS_MULTIPROC_DIR = BASE_DIR / ".prometheus_multiproc"
PROMETHEUS_MULTIPROC_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("PROMETHEUS_MULTIPROC_DIR", str(PROMETHEUS_MULTIPROC_DIR))

# ---------------------------------------------------------------------------
# Sentry (PRD §13) — DSN is optional; an empty/missing DSN makes the SDK a
# documented no-op (never sends events, never errors), so this works
# identically before and after you create a free-tier Sentry project.
# traces_sample_rate=1.0 traces every request, profile_session_sample_rate=1.0
# profiles every traced session -- fine at this project's laptop-scale
# traffic; turn both down (e.g. 0.1-0.2) if ever pointed at real production
# volume. send_default_pii=True is safe here since the app only ever handles
# seeded/mock data (PRD §3 non-goals) -- no real user PII exists to leak.
# enable_logs is left off -- this project's Sentry plan/project rejects
# log_item envelopes with a 403 (verified during setup); it's a separate,
# newer Sentry feature unrelated to error/performance capture, both of
# which work without it.
# ---------------------------------------------------------------------------

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""),
    integrations=[DjangoIntegration()],
    send_default_pii=True,
    traces_sample_rate=1.0,
    profile_session_sample_rate=1.0,
    profile_lifecycle="trace",
)

# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-fallback-key-change-in-env",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# ---------------------------------------------------------------------------
# Application definition
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    # Local apps
    "apps.screens",
    "apps.flags",
    "apps.funds",
    "apps.serving",
    "apps.common",
]

REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
}

MIDDLEWARE = [
    "apps.common.middleware.PrometheusMetricsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------------------
# Database — PostgreSQL on 127.0.0.1:5432
# ---------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "sdui_dev"),
        "USER": os.environ.get("DB_USER", "sdui_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "5433"),
    }
}


# ---------------------------------------------------------------------------
# Cache — Redis on 127.0.0.1:6379
# ---------------------------------------------------------------------------

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            # Without these, a down/unreachable Redis blocks each cache
            # operation for redis-py's default timeout, which stacks up
            # fast across the ~10 cache calls one screen request makes
            # (measured ~8-12s for a single request with Redis down).
            # This bounds it to a fixed worst case per call; the real
            # fix (a circuit breaker that skips Redis entirely after
            # repeated failures) is still deferred -- see apps/common/cache.py.
            "socket_connect_timeout": 0.2,
            "socket_timeout": 0.2,
        },
    }
}


# ---------------------------------------------------------------------------
# Celery — broker and result backend both use Redis
# ---------------------------------------------------------------------------

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Without these, a down/unreachable broker blocks .delay() for redis-py's
# default connection timeout -- the same problem the cache OPTIONS above
# solve, for the same reason (Phase 5, mirrors commit d39ac73). Callers of
# .delay() (apps/screens/services.py, apps/funds/models.py) catch
# kombu.exceptions.OperationalError and fall back to synchronous work.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "socket_connect_timeout": 0.2,
    "socket_timeout": 0.2,
}

# Hardcoded for Phase 5 per PRD §16 ("hardcode first, migrate to
# django-celery-beat once the admin panel needs to control schedules").
CELERY_BEAT_SCHEDULE = {
    "recompute-top-movers": {
        "task": "apps.funds.tasks.recompute_top_movers",
        "schedule": 300.0,  # every 5 min (PRD §10)
    },
    "recompute-trending": {
        "task": "apps.funds.tasks.recompute_trending",
        "schedule": 900.0,  # every 15 min (PRD §10)
    },
    "recompute-recommended-funds": {
        "task": "apps.funds.tasks.recompute_recommended_funds",
        "schedule": 900.0,  # every 15 min, mirrors recompute-trending (Phase 8)
    },
    "recompute-all-portfolio-snapshots": {
        "task": "apps.funds.tasks.recompute_all_portfolio_snapshots",
        "schedule": crontab(hour=1, minute=30),  # daily, post-NAV window (PRD §9A)
    },
    "retry-failed-portfolio-recomputes": {
        "task": "apps.funds.tasks.retry_failed_portfolio_recomputes",
        "schedule": 900.0,  # every 15 min; self-heals DLQ rows (plan.md §14)
    },
}


# ---------------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
